### ISSUE TITLE
How to add remote image fetching ?

### ISSUE THREAD

**Issue by rblanch** [lencioni/SLIR#20] opened 2013-08-19 15:43 UTC
Hi 
You have remote image fetching in your TO DO

I am willing to code this feature because I need it myself.

Can you give me some guidance? 
Tell me where to put the method and how to name it and I can submit a pull request

**Comment by ambroisemaupate** [comment] 2015-05-20 21:52
Duplicate of #16

**Closed by ambroisemaupate** 2015-05-20 21:52 UTC
